name: Duplicate Issue For OpenDocumentationAcademy

on:
  issues:
    types: [labeled]

jobs:
  duplicate-issue:
    if: ${{ github.event.label.name == 'OpenDocumentationAcademy' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Issue Details
        uses: actions/github-script@v7
        id: get_issue
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context, GitHub } = require('@actions/github');
            const github = new GitHub(process.env.GITHUB_TOKEN);
            const { owner, repo, issue } = context.payload;
            const issueDetails = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number
            });
            console.log(issueDetails.data);
            return issueDetails.data;

      - name: Create Issue in ODA Repository
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.ODA_REPO_TOKEN }}
          script: |
            const { context2, GitHub } = require('@actions/github');
            const github = new GitHub(process.env.GITHUB_TOKEN);
            const issueData = await github.issues.create({
              owner: 'canonical',  // The owner of the upstream repo
              repo: 'open-documentation-academy',    // Replace 'target-repo' with the name of the target repository
              title: '${{ steps.get_issue.outputs.title }}',
              body: '${{ steps.get_issue.outputs.body }}\n\nOriginal Issue: [Original Issue](${{ steps.get_issue.outputs.html_url }})'
            });
            console.log(`Issue created: ${issueData.data.html_url}`);